<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\InventoryManagement;
use App\Models\Product;

class InventoryManagementSeeder extends Seeder
{
    public function run()
    {
        // Asegurarse de tener productos previamente sembrados
        $products = Product::all();

        foreach ($products as $product) {
            // Generar 2-5 movimientos por producto
            InventoryManagement::factory()->count(rand(2,5))->state(function () use ($product) {
                $stockAntes = (float) $product->stock;
                $tipo = ['entrada','salida','ajuste'][array_rand(['entrada','salida','ajuste'])];
                if ($tipo === 'entrada') {
                    $cantidad = rand(1,50);
                    $stockDespues = $stockAntes + $cantidad;
                } elseif ($tipo === 'salida') {
                    $cantidad = min(rand(1,50), max(0.001, (int)$stockAntes));
                    $stockDespues = $stockAntes - $cantidad;
                } else {
                    $stockDespues = max(0, $stockAntes + rand(-20,50));
                    $cantidad = abs($stockDespues - $stockAntes);
                }

                // actualizar producto stock para consistencia
                $product->stock = $stockDespues;
                $product->save();

                return [
                    'product_id' => $product->id,
                    'stock_antes' => $stockAntes,
                    'stock_despues' => $stockDespues,
                    'cantidad' => $cantidad,
                    'tipo_movimiento' => $tipo,
                    'motivo' => 'Seed autogenerated',
                ];
            })->create();
        }
    }
}