<?php

namespace Database\Seeders;

use App\Models\InventoryManagement;
use App\Models\Product;
use Illuminate\Database\Seeder;

class InventoryManagementSeeder extends Seeder
{
    public function run()
    {
        // Asegurarse de tener productos previamente sembrados
        $products = Product::all();

        foreach ($products as $product) {
            // Generar 2-5 movimientos por producto
            InventoryManagement::factory()->count(rand(2, 5))->state(function () use ($product) {
                $stockBefore = (float) $product->stock;
                $type = ['inbound', 'outbound', 'adjustment'][array_rand(['inbound', 'outbound', 'adjustment'])];
                if ($type === 'inbound') {
                    $quantity = rand(1, 50);
                    $stockAfter = $stockBefore + $quantity;
                } elseif ($type === 'outbound') {
                    $quantity = min(rand(1, 50), max(0.001, (int) $stockBefore));
                    $stockAfter = $stockBefore - $quantity;
                } else {
                    $stockAfter = max(0, $stockBefore + rand(-20, 50));
                    $quantity = abs($stockAfter - $stockBefore);
                }

                // actualizar producto stock para consistencia
                $product->stock = $stockAfter;
                $product->save();

                return [
                    'product_id' => $product->id,
                    'stock_before' => $stockBefore,
                    'stock_after' => $stockAfter,
                    'quantity' => $quantity,
                    'movement_type' => $type,
                    'reason' => 'Seed autogenerated',
                ];
            })->create();
        }
    }
}
